version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "4173:4173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    env_file:
      - .env
